apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp-chart.fullname" . }}-config
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
data:
  APP_MESSAGE: {{ .Values.appConfig.message | quote }}